FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY requirements/base.txt requirements/data.txt requirements/cloud.txt requirements/ml.txt ./
RUN pip install --no-cache-dir --default-timeout=1000 -r base.txt && \
    pip install --no-cache-dir --default-timeout=1000 -r data.txt && \
    pip install --no-cache-dir --default-timeout=1000 -r cloud.txt && \
    pip install --no-cache-dir --default-timeout=1000 -r ml.txt

COPY streaming ./streaming
COPY schemas ./schemas

CMD ["python", "-m", "streaming.kafka_consumer"]
